### ISSUE TITLE
Most examples are not shown

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-maps#24] opened 2017-03-10 13:57 UTC
Position, camera and region examples don't display a map. Marker example shows a map, but it doesn't have expected size: 

![screenshot_1489154132](https://cloud.githubusercontent.com/assets/2341769/23797749/9eb9360a-05a1-11e7-82bb-7aae2ef79a08.png)

May be related to example layout.

**Comment by mpost** [comment] 2017-03-13 15:51
The problem is introduced with the migration to the ConstraintLayout in tabris-android 2.0.0-beta2. It is related to https://code.google.com/p/android/issues/detail?id=246371 and must be fixed int the ConstraintLayout library.

**Closed as completed** 2017-08-29 13:16 UTC
Labels: bug, Android
